# Generated by Django 5.2.11 on 2026-02-12 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('alt_text', models.CharField(blank=True, max_length=500, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('credit', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Media',
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='RawNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('traite', 'Traite'), ('ignore', 'Ignore')], default='nouveau', max_length=10)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Raw news',
                'db_table': 'raw_news',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('rss', 'RSS'), ('api', 'API'), ('scraper', 'Scraper')], max_length=10)),
                ('url', models.TextField()),
                ('fetch_interval', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('game', 'Game'), ('platform', 'Platform'), ('genre', 'Genre'), ('general', 'General')], default='general', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='articles.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('content', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('featured_image', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('brouillon_ia', 'Brouillon IA'), ('en_revision', 'En Revision'), ('publie', 'Publie'), ('archive', 'Archive')], default='nouveau', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_breaking', models.BooleanField(default=False)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('validation_notes', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.category')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.media')),
            ],
            options={
                'db_table': 'article_media',
                'ordering': ['order_position'],
                'unique_together': {('article', 'media')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.ManyToManyField(related_name='articles', through='articles.ArticleMedia', to='articles.media'),
        ),
        migrations.AddField(
            model_name='article',
            name='raw_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.rawnews'),
        ),
        migrations.AddField(
            model_name='rawnews',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_news', to='articles.source'),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.source'),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.tag')),
            ],
            options={
                'db_table': 'article_tags',
                'unique_together': {('article', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', through='articles.ArticleTag', to='articles.tag'),
        ),
    ]
