# Generated by Django 5.2.11 on 2026-04-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_add_comment_model'),
        ('articles', '0003_newslettersubscriber'),
    ]

    operations = [
    ]
