# Generated by Django 5.2.13 on 2026-04-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_add_sitesettings_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_b64',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
