# Generated by Django 5.2.11 on 2026-04-27 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_featured_image_b64'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('hero', 'Hero Section'), ('trending', 'Trending Now'), ('latest', 'Latest Grid'), ('game_news', 'Game News'), ('hardware', 'Hardware'), ('esports', 'Esports'), ('culture', 'Culture'), ('category', 'Category Section')], max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('article_count', models.PositiveIntegerField(default=6)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_sections', to='articles.category')),
            ],
            options={
                'db_table': 'landing_sections',
            },
        ),
        migrations.CreateModel(
            name='LandingSectionArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_placements', to='articles.article')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_articles', to='articles.landingsection')),
            ],
            options={
                'db_table': 'landing_section_articles',
                'ordering': ['position'],
                'unique_together': {('section', 'article')},
            },
        ),
    ]
