# Generated by Django 5.2.13 on 2026-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_featured_image_b64'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('short_description', models.CharField(blank=True, default='', max_length=500)),
                ('image_url', models.TextField(blank=True, default='')),
                ('release_display', models.CharField(blank=True, default='TBA', max_length=100)),
                ('players', models.CharField(blank=True, default='', max_length=50)),
                ('trend', models.CharField(blank=True, default='', max_length=20)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('game_type', models.CharField(choices=[('popular', 'Popular'), ('anticipated', 'Anticipated'), ('both', 'Both')], default='popular', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='games', to='articles.category')),
            ],
            options={
                'db_table': 'games',
                'ordering': ['rank', 'title'],
            },
        ),
    ]
