# Generated by Django 5.2.11 on 2026-04-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0007_article_featured_image_b64'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('cover_image', models.URLField(blank=True, max_length=2000)),
                ('trailer_url', models.URLField(blank=True, max_length=2000)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('platforms', models.JSONField(default=list)),
                ('developer', models.CharField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_display', models.CharField(blank=True, default='TBA', max_length=50)),
                ('game_type', models.CharField(choices=[('popular', 'Popular'), ('anticipated', 'Anticipated'), ('both', 'Both')], default='popular', max_length=20)),
                ('status', models.CharField(blank=True, choices=[('coming_soon', 'Coming Soon'), ('tba', 'TBA'), ('released', 'Released')], default='coming_soon', max_length=20)),
                ('hype_score', models.IntegerField(default=80)),
                ('popularity_score', models.IntegerField(default=75)),
                ('player_count', models.CharField(blank=True, max_length=50)),
                ('metacritic', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(db_index=True, default=0)),
                ('trend', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='games', to='articles.category')),
            ],
            options={
                'db_table': 'games',
                'ordering': ['rank', '-created_at'],
            },
        ),
    ]
